### ISSUE TITLE
Import Microsoft threat-model (.tm4) format

### ISSUE THREAD

**Issue by kallada** [mozilla/seasponge#4]
The current most popular tool for threat modeling is the the Microsoft Threat Modelling Tool. This tool uses an XML based format for storing threat models. A user can import threat models that have been created using the Microsoft tool.

**Comment by Glavin001** [comment]
So XSLT is pretty cool. 

Here's a way to convert XML to JSON: http://www.bramstein.com/projects/xsltjson/

**Comment by rainbee2214** [comment]
We have changed our schema so much from our original plan that it is not feasible to import a Microsoft threat model. We found that the Microsoft threat modeling tool is actually very different from the Seasponge tool.

**Comment by Glavin001** [comment]
I would about developing a partial converter? While there are significant differences, SeaSponge can be very flexible and would likely work for the most part to import basic stencil elements and create their flows.
