### ISSUE TITLE
Data Classification & Security Controls

### ISSUE THREAD

**Issue by Glavin001** [mozilla/seasponge#40]
- [x] `Data Classifications` and `Security Controls`
  - [x] adding
  - [x] editing
    - [x] title
    - [x] type
  - [x] removing
- [x] serialize
- [x] deserialize
- Import more `Data Classifications` and `Security Control` options, see #44

**Comment by Frozenfire92** [comment]
The dropdowns will take in a configuration file at time of model creation to allow for different companies workflows. Here is an example 

```
data classification:

[ free field ]   [ dropdown: {public, internal, restricted, secret} ]
[ free field ]   [ dropdown: {public, internal, restricted, secret} ]
[ free field ]   [ dropdown: {public, internal, restricted, secret} ]
[ free field ]   [ dropdown: {public, internal, restricted, secret} ]

security controls:

[ free field ]   [ dropdown: {confidentiality, integrity, availability} ]
[ free field ]   [ dropdown: {confidentiality, integrity, availability} ]
[ free field ]   [ dropdown: {confidentiality, integrity, availability} ]
[ free field ]   [ dropdown: {confidentiality, integrity, availability} ]
```

**Comment by Glavin001** [comment]
![image](https://cloud.githubusercontent.com/assets/1885333/5650853/809889cc-9678-11e4-8e19-81e7cd75a68b.png)

**Comment by Glavin001** [comment]
![image](https://cloud.githubusercontent.com/assets/1885333/5663077/5b9d98a6-9718-11e4-918b-c512ab6cc729.png)

**Comment by Glavin001** [comment]
@Frozenfire92 , do you mind taking a look at this once it's finished deploying. Let me know what you think :smile:

**Comment by Glavin001** [comment]
I have moved the `import more options` to #44. Therefore, this is complete.
