### ISSUE TITLE
Sharable Link

### ISSUE THREAD

**Issue by Glavin001** [mozilla/seasponge#41]

**Comment by kallada** [comment]
If this a client-side application - how do you efficiently intend on creating a shareable link?

**Comment by Glavin001** [comment]
![image](https://cloud.githubusercontent.com/assets/1885333/5675613/46f1f498-9799-11e4-8fae-a611d67ec13d.png)

**Comment by Glavin001** [comment]
@kallada the implementation has been pushed, so feel free to look at the source code.

The basic idea is that we can serialize a `Model` as JSON and then into a string. This string can be encoded and set as a query-param in a URL. We generate a URL that has the query-param. In our case, we have a `/load` route that we pass `model` query parameter to, and the `LoadController` knows how to detect the existence of `model` query-param and then load it from the string.
It works analogous to our current `Open File`, except the source of the Model data is instead from the query parameter instead of the file contents.

**Comment by Frozenfire92** [comment]
I like it :smile: 

However I think we should remove the refresh link button, and whenever it gains focus auto refresh it, or have a copy to clipboard button similar to github's clone link, and refresh it before we copy it.

I think we could use [this](https://github.com/asafdav/ng-clip) library

**Comment by kallada** [comment]
Interesting - I am imagining that if our saving mechanism isn't efficient enough, we would be passing around extremely large URLs.

**Comment by Glavin001** [comment]
Yup, it could get fairly long. It's definitely not designed to be the primary way of sharing, just a simple way.

Also see [What is the maximum possible length of a query string?](http://stackoverflow.com/a/812962/2578205).

We could use a URL shortener: http://stackoverflow.com/questions/12696704/using-javascript-to-access-googles-url-shortener-apis-in-a-google-chrome-extens

Cloud Storage ( #19 ) should supersede this feature.

**Comment by jvehent** [comment]
This looks good and probably serves the need well enough. Don't worry too much about making it perfect. We can pass JSON documents around for the time being.
