### ISSUE TITLE
Model loading creating curved and incorrectly-positioned Flows

### ISSUE THREAD

**Issue by Glavin001** [mozilla/seasponge#42]
- [x] Save/Load
- [x] Switching diagrams

**Comment by kallada** [comment]
Normal

![normal](http://i57.tinypic.com/2r6chzb.png)

Save/lload

![wtf](http://i57.tinypic.com/2r6chzb.jpg)

**Comment by Glavin001** [comment]
Thanks for posting those screenshots, @kallada.

We should pick a default and then pass those configurations around to the functions that build the endpoints. I actually like the curved lines. Which do you guys think we should use, curved or straight?

Configs for endpoints: https://github.com/mozilla/seasponge/blob/master/app/scripts/stencils/base.coffee#L208-L288
Build endpoints for Stencil Element: https://github.com/mozilla/seasponge/blob/master/app/scripts/stencils/base.coffee#L105-L122

**Comment by kallada** [comment]
Weird feeling about this:

                # Render Flows
                instance.connect({
                    source: flow.sourceId
                    target: flow.targetId
                    }) for flow in @flows

From here, I can easily change the style of the connections however, @Glavin001 are we saving anchors (also known as endpoints) from the diagram? That would be why endpoints connections are not in the right positions.

**Comment by Glavin001** [comment]
> from diagram.coffee

For reference and context, here's the link: https://github.com/mozilla/seasponge/blob/master/app/scripts/services/diagram.coffee#L148-L152

---
> are we saving anchors (also known as endpoints) from the diagram? 

Yup. Here: https://github.com/mozilla/seasponge/blob/master/app/scripts/services/diagram.coffee#L92-L95
We save the identifiers / names for the flows.

>  That would be why endpoints connections are not in the right positions.

Is this still an issue? Could you post a screenshot please? That'd be a bug for sure.

We should be using [@anchors](https://github.com/mozilla/seasponge/blob/master/app/scripts/stencils/base.coffee#L9) for each Stencil and combine with [@shape](https://github.com/mozilla/seasponge/blob/master/app/scripts/stencils/base.coffee#L12) to allow us to have complex shapes and anchor positions. Each anchor has a unique name and these are what we (de)serialize.

However, currently the anchors are hardcoded: https://github.com/mozilla/seasponge/blob/master/app/scripts/stencils/base.coffee#L84-L90

**Comment by Frozenfire92** [comment]
> Is this still an issue? Could you post a screenshot please? That'd be a bug for sure.

See the screenshot above, when recreating the diagram it always uses the bottom anchor/connection

**Comment by Glavin001** [comment]
Oh I didn't even notice. Thanks for pointer.

I'd recommend looking at [saving/serializing](https://github.com/mozilla/seasponge/blob/master/app/scripts/services/diagram.coffee#L92-L95) and also at [loading/rendering](https://github.com/mozilla/seasponge/blob/master/app/scripts/services/diagram.coffee#L148-L152) and see if there are any differences in the `targetId` and `sourceId` between execution. From my (limited) understanding of jsPlumb, what we are doing should be working: remember the unique identifiers for the `target` and `source` of each Flows and then re-connect those at render. See https://github.com/mozilla/seasponge/blob/master/app/scripts/stencils/base.coffee#L84-L90
for list of anchors.
It looks as if https://github.com/mozilla/seasponge/blob/master/app/scripts/services/diagram.coffee#L149-L152

```javascript
# Render Flows
                instance.connect({
                // could end with "TopCenter", "BottomCenter", "LeftMiddle", "RightMiddle"
                    source: flow.sourceId
                    target: flow.targetId
                    }) for flow in @flows
```

Is actually running like:

```javascript
# Render Flows
                instance.connect({
                    source: "#{sourceElementId}BottomCenter" 
                    target: "#{targetElementId}BottomCenter"
                    }) for flow in @flows
```

This is wack.

**Comment by Glavin001** [comment]
@Frozenfire92 would you like to tackle this one? I'm going to try and resolve those new issues. Let me know. Thanks!

**Comment by Glavin001** [comment]
Looks like the `targetId` and `sourceId` are just the Elements and not their Endpoints/Anchors.

See http://www.jsplumb.org/doc/connect-examples.html for more examples of connecting endpoints in jsPlumb.
Specifically an example such as:
> Connect window3 to 'window4' with a 10 pixel wide, semi opaque blue Connector, anchored to the left middle of window3, and the right middle of window4, with a Rectangle endpoint of width 10 and height 8:
>
>```javascript
jsPlumb.connect({
  source:'window3',
  target:'window4',
  paintStyle:{ lineWidth:10, strokeStyle:'rgba(0, 0, 200, 0.5)' },
  anchors:["Right", "Left"],
  endpoint:[ "Rectangle", { width:10, height:8 } ]
});
```

Notice the inclusion of `anchors` field, along with `source` and `target`.
We should 
- [ ] serialize the Flows' (Connections') `anchor`
- [ ] deserialize and render Flows (Connections) with specified `anchor`

**Comment by Glavin001** [comment]
Instead of using `source`, `target` and `anchor`s, using the UUIDs. See http://stackoverflow.com/a/22264487/2578205

**Comment by Glavin001** [comment]
All good now!
![seasponge-flows](https://cloud.githubusercontent.com/assets/1885333/5831202/f7a7a30a-a103-11e4-85a0-faf1e883a074.gif)
