### ISSUE TITLE
Pressing [Enter] will submit the `Delete Element` button and delete the selected Element

### ISSUE THREAD

**Issue by Glavin001** [mozilla/seasponge#53]
## Reproduce
- Select Element
- Click `Enter Title` field
- Press [Enter]
- Element disappears

![seasponge-delete-element-bug](https://cloud.githubusercontent.com/assets/1885333/5839103/557b73e0-a162-11e4-9aeb-5578cc1bc6d8.gif)

**Comment by kallada** [comment]
@Glavin001 Side note: What tool did you use to make that .gif?

**Comment by Glavin001** [comment]
http://www.cockos.com/licecap/

**Comment by Glavin001** [comment]
Solution from: http://stackoverflow.com/a/1977126/2578205
