### ISSUE TITLE
Implement copy for existing screen elements

### ISSUE THREAD

**Issue by jeffbryner** [mozilla/seasponge#56]
Often when drawing you have an element you'd like to reproduce (icon, name, tags, etc) several times on the diagram like processes, users, etc. 

Currently you can do this by adding the same stencil multiple times and manually changing the attributes to be the same, but it would be easier if there was a 'copy element' option to facilitate.

**Comment by Glavin001** [comment]
+1

---

- [ ] Allow for selecting multiple elements/flows when shift/control/command key is being held
- [ ] `oncopy`, serialize the selected objects
- [ ] `onpaste`, deserialize the objects from clipboard and add to current diagram
  - [ ] offset / translate the position of these elements such that they do not get pasted directly on top of the original elements, such that the user cannot see that they have been successfully created
- [ ] right-click / context-menu for "Duplicate"
  - accomplishes same clone/copy of selected elements, without copy+paste user action

Related links:
- http://stackoverflow.com/questions/400212/how-do-i-copy-to-the-clipboard-in-javascript
- https://github.com/mojombo/clippy
- http://steamdev.com/zclip/
- https://developer.mozilla.org/en-US/docs/Web/Events/paste

**Comment by Glavin001** [comment]
This guide is great! https://www.lucidchart.com/techblog/2014/12/02/definitive-guide-copying-pasting-javascript/

**Comment by Glavin001** [comment]
^ While `window.clipboardData` would be great, it appears not to work.

I am going to opt for an in-app, SeaSponge specific "clipboard".

**Comment by Glavin001** [comment]
Currently only single elements will be selectable at a time and copy/paste-able. 
Right-click / context menu is also coming later.

![seasponge_copy_paste](https://cloud.githubusercontent.com/assets/1885333/6955823/6c70f14e-d8ba-11e4-87e4-003443d4f7dd.gif)

**Comment by Glavin001** [comment]
Pushed. Should be available now in a few minutes. Thank you for your patients.
