### ISSUE TITLE
Wiki Images

### ISSUE THREAD

**Issue by Frozenfire92** [mozilla/seasponge#62]
Currently you can't upload images to github wikis, this issue will serve as hosting for said images

**Comment by Frozenfire92** [comment]
![basicusage](https://cloud.githubusercontent.com/assets/5893112/6827282/55cf9060-d2e5-11e4-802f-7663719ee873.gif)
![creation](https://cloud.githubusercontent.com/assets/5893112/6827283/55da7ac0-d2e5-11e4-8562-8ae881be2e29.gif)

**Comment by Glavin001** [comment]
I'm going to close this: we can still use it to store more images, if necessary. :+1:
