### ISSUE TITLE
Cannot create flows to multiple targets

### ISSUE THREAD

**Issue by sbmilburn** [mozilla/seasponge#64]
Scenario #1 - Need to be able to create a load balancer object and then 1..N webservers. Tried to have the flow go to mutliple webservers but currently it only allows you to select a single target. 

Secenario #2 - Some of our web applications talk to multiple databases. One for OLTP transactions and one for pulling reports. having the ability to have the link a flow to more than one target location would be helpful.

**Comment by Glavin001** [comment]
I can see your use cases being very common and high priority. Thank you for sharing. 

We should be able to use jsPlumb's `maxconnections` setting for sources to resolve this. See https://jsplumbtoolkit.com/doc/connections.html for more details. The applicable section of SeaSponge code is at  https://github.com/mozilla/seasponge/blob/master/app/scripts/stencils/base.coffee#L129-L147

I'll try and do some testing with this later today.

**Comment by Glavin001** [comment]
This demo appears to have multiple output connections: https://jsplumbtoolkit.com/demo/sourcesAndTargets/dom.html

**Comment by Glavin001** [comment]
I have a working demo of multiple connections from source endpoints:
![image](https://cloud.githubusercontent.com/assets/1885333/6948791/7d255216-d886-11e4-8d16-aab8304663f5.png)

We should look into the `filter` function and how certain endpoints can only connect with another subset of endpoints. The more feedback we receive and example use cases the better we can make this.

**Comment by Glavin001** [comment]
Pushed this feature. Should be available soon. Let me know if it works for you. Thanks!
