### ISSUE TITLE
App initiation sits at "watch" task

### ISSUE THREAD

**Issue by cgalligan** [mozilla/seasponge#71]
When running $grunt serve or $grunt serve:docs, the process consistently hangs at "Running "watch" task", is this expected behavior? How long does this process take?

**Comment by Frozenfire92** [comment]
Hi @cgalligan

This is expected behaviour. What watch does it continually check the directory for any changes. That way during development the locally served copy will be updated as you change files. Let me know if there is anything else that needs clarification!
