### ISSUE TITLE
Update Connect Task to Start Web Server on Hostname/ IP

### ISSUE THREAD

**Issue by cgalligan** [mozilla/seasponge#72]
This is probably really simple, but how do I edit the code so that the webserver is accessible via hostname or server IP? Right now the connect task starts the process on localhost.

**Comment by Glavin001** [comment]
Good question.

See https://github.com/mozilla/seasponge/blob/master/Gruntfile.coffee#L78-L79
You can change `hostname` to `0.0.0.0` and that should do it.

**Comment by cgalligan** [comment]
Thanks this was exactly what I was looking for
