### ISSUE TITLE
Export threat model to image/HTML/PDF

### ISSUE THREAD

**Issue by Glavin001** [mozilla/seasponge#8]
[Easy] The user may want to export an image of the threat model itself for presentation purposes. The user will be able to set the resolution or page size preferences upon export or print. With jsPlumb this should be fairly easy to add.

**Comment by Glavin001** [comment]
Currently some of the layers are rendered out of order. 

- [ ] Render each layer on their own canvas
- [ ] merge canvas layers, see http://stackoverflow.com/questions/3750580/save-many-canvas-element-as-image/3797989#3797989

**Comment by Pana** [comment]
In my situation the color is a little different as the jsplumb chart and some css effect is not render normally such as the dotted border: 1px dotted gray , this may the issue of html2canvas

**Comment by Glavin001** [comment]
Thanks for letting us know, @Pana. I think we can migrate these into a separate bug Issue.

**Comment by Pana** [comment]
I have try canvg on IE11, but it didn't work on it
