### ISSUE TITLE
Application Doesn't Load

### ISSUE THREAD

**Issue by cgalligan** [mozilla/seasponge#80]
When running # grunt serve or # grunt serve:docs; the application appears to load based on the command line output; however when we try to browse to the application we get the Seasponge logo on the tab, but a blank page. Is there another command we should run to initiate the application?

**Comment by michaelpjohnson** [comment]
+1 
I get the same output. I can view the source and see that the server returned code, but my browser doesn't render anything. I can also visit: http://127.0.0.1:35729/livereload.js?snipver=1 and get code to return as well.

**Comment by michaelpjohnson** [comment]
@cgalligan If you actually merge the pending PR then it works. I just copied the raw file https://raw.githubusercontent.com/SimplicityGuy/seasponge/master/bower.json and re-ran the npm/bower installs. Works for me now.

**Comment by Frozenfire92** [comment]
Merged the PR, sorry about the delay. Feel free to reopen if that didn't fix it

**Comment by michaelpjohnson** [comment]
@Frozenfire92 I pulled a fresh copy and re-installed from the PR. It works perfectly now. Thanks for all the work you and the team have put into this.
